services:
  tecas-db-19:
    image: pgvector/pgvector:pg15
    container_name: tecas-db-19
    restart: unless-stopped
    environment:
      POSTGRES_DB: tecas19
      POSTGRES_USER: odoo19
      POSTGRES_PASSWORD: odoo
    volumes:
      - tecas-db-data:/var/lib/postgresql/data
    networks:
      - tecas-v19-net

  tecas-web-19:
    build: .
    image: tecas-web:v19
    container_name: tecas-web-19
    restart: unless-stopped
    depends_on:
      - tecas-db-19
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - tecas-filestore:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/user-addons
    command: odoo --config /etc/odoo/odoo.conf
    networks:
      - tecas-v19-net

volumes:
  tecas-db-data:
  tecas-filestore:
    external: true
    name: tecas-v19_tecas-filestore

networks:
  tecas-v19-net:
    driver: bridge
